version: "3.8"

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITD_ROOT_USERNAME: key-race
      MONGO_INITD_ROOT_PASSWORD: key-race
    volumes:
      - ~/apps/mongo:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: key-race
      ME_CONFIG_MONGODB_ADMINPASSWORD: key-race
      ME_CONFIG_MONGODB_URL: mongodb://key-race:key-race@mongo:27017/
